name: Generate Datas
on:
  schedule:
    - cron: "* */12 * * *" # Executes every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: danibarrosj
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages # Ensure this matches your Pages branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
